-- SECUENCIAS 

CREATE SEQUENCE seq_cantantes START WITH 1 INCREMENT BY 1 NOMAXVALUE;
CREATE SEQUENCE seq_fechaGrabacion START WITH 1 INCREMENT BY 1 NOMAXVALUE;

-- En la tabla studios_grabaciones no es necesario crear una secuencia debido a que ya tiene incorporado el autoincremental 
-- en la columna id_studio_grabacion (GENERATED BY DEFAULT AS IDENTITY)