-- Tablas

CREATE TABLE cantantes(
     id_cantante NUMBER PRIMARY KEY,
     nombre VARCHAR2(50) NOT NULL,
     cantidad_cantantes NUMBER DEFAULT 1,
     genero_musical VARCHAR2(100) NOT NULL

)

CREATE TABLE studios_grabaciones(
     id_studio_grabacion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     nombre_studio VARCHAR2(50) NOT NULL,
     id_cantante NUMBER NOT NULL
)
     ALTER TABLE studios_grabaciones
     ADD CONSTRAINT fk_cantante_studio FOREIGN KEY (id_cantante) REFERENCES cantantes(id_cantante);
     
CREATE TABLE fecha_grabacion(
     id_fecha_grabacion NUMBER PRIMARY KEY,
     fecha DATE NOT NULL,
     id_cantante NUMBER NOT NULL,
     id_studio_grabacion NUMBER NOT NULL,
     
     CONSTRAINT fk_cantante_fecha FOREIGN KEY (id_cantante) REFERENCES cantantes(id_cantante),
     CONSTRAINT fk_studio_fecha FOREIGN KEY (id_studio_grabacion) REFERENCES studios_grabaciones(id_studio_grabacion)
)